# Generated by Django 6.1.1 on 2026-09-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreequipe',
            name='section',
            field=models.CharField(default='Coordination', max_length=100, verbose_name='Section'),
        ),
    ]
