# Generated by Django 6.1.1 on 2026-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_membreequipe_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['type', 'nom', 'logo'], 'verbose_name': 'Partenaire / Sponsor', 'verbose_name_plural': 'Partenaires & Sponsors'},
        ),
        migrations.RenameField(
            model_name='partenaire',
            old_name='tier',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='role',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='site_web',
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom du sponsor'),
        ),
    ]
