# Generated by Django 6.1.1 on 2026-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_partenaire_options_rename_tier_partenaire_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='type',
            field=models.CharField(choices=[('pays', 'Pays'), ('institution', 'Institution'), ('ong', 'ONG'), ('ambassade', 'Ambassade')], default='argent', max_length=20, verbose_name='Niveau / Palier'),
        ),
    ]
